name: machine learning

services:

  jupyter:
    build:
      dockerfile_inline: |
        FROM jupyter/scipy-notebook:latest
        RUN pip install --no-cache-dir pandas matplotlib seaborn scikit-learn xgboost lightgbm catboost
    ports:
      - 8888:8888

    environment:
      JUPYTER_TOKEN: F9ooYRXVAiPzK7PfkeIWAoxadG5LRqGepkRMBwz7PiZbx3sArtGP8FAAuPzvWFb7   # ← escolha um token fixo (bem mais fácil)
      JUPYTER_ENABLE_LAB: yes   # já é padrão nas imagens recentes
    # volumes:
    #   - ./notebooks:/home/jovyan/work   # ← seus arquivos locais aparecem no container
    command: start-notebook.sh --NotebookApp.token='${JUPYTER_TOKEN}' --ip=0.0.0.0